# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: ci
    groups:
      all-actions:
        patterns: ['*']
    schedule:
      interval: weekly
